"""add_cookie_status_to_agents

Revision ID: 6f27ca2e7a16
Revises: 089e17751f36
Create Date: 2026-02-27 08:03:43.518744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f27ca2e7a16'
down_revision: Union[str, None] = '089e17751f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('agents', sa.Column(
        'cookie_status', sa.String(length=20),
        nullable=False, server_default='unknown',
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'cookie_status')
    # ### end Alembic commands ###
