"""add_sync_tables_v2

Revision ID: 7d03c8a93299
Revises: a1b2c3d4e5f6
Create Date: 2026-02-27 00:06:59.541111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d03c8a93299'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_third_party',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=250), nullable=False),
    sa.Column('platform_id_name', sa.String(length=200), nullable=True),
    sa.Column('platform_username', sa.String(length=200), nullable=True),
    sa.Column('c_name', sa.String(length=200), nullable=True),
    sa.Column('game_name', sa.String(length=200), nullable=True),
    sa.Column('bet_amount', sa.String(length=50), nullable=True),
    sa.Column('turnover', sa.String(length=50), nullable=True),
    sa.Column('prize', sa.String(length=50), nullable=True),
    sa.Column('win_lose', sa.String(length=50), nullable=True),
    sa.Column('bet_time', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_third_party_agent_id'), 'bet_third_party', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bet_third_party_serial_no'), 'bet_third_party', ['serial_no'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.Column('lottery_name', sa.String(length=200), nullable=True),
    sa.Column('play_type_name', sa.String(length=200), nullable=True),
    sa.Column('play_name', sa.String(length=200), nullable=True),
    sa.Column('issue', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('money', sa.String(length=50), nullable=True),
    sa.Column('rebate_amount', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('status_text', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_agent_id'), 'bets', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bets_serial_no'), 'bets', ['serial_no'], unique=False)
    op.create_index(op.f('ix_bets_username'), 'bets', ['username'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_parent_format', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_agent_id'), 'deposits', ['agent_id'], unique=False)
    op.create_index(op.f('ix_deposits_username'), 'deposits', ['username'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('reg_count', sa.Integer(), nullable=False),
    sa.Column('scope_reg_count', sa.Integer(), nullable=False),
    sa.Column('recharge_count', sa.Integer(), nullable=False),
    sa.Column('first_recharge_count', sa.Integer(), nullable=False),
    sa.Column('register_recharge_count', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_agent_id'), 'invites', ['agent_id'], unique=False)
    op.create_index(op.f('ix_invites_invite_code'), 'invites', ['invite_code'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('type_format', sa.String(length=50), nullable=True),
    sa.Column('parent_user', sa.String(length=100), nullable=True),
    sa.Column('money', sa.String(length=50), nullable=True),
    sa.Column('deposit_count', sa.Integer(), nullable=False),
    sa.Column('withdrawal_count', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_amount', sa.String(length=50), nullable=True),
    sa.Column('login_time', sa.String(length=50), nullable=True),
    sa.Column('register_time', sa.String(length=50), nullable=True),
    sa.Column('status_format', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_agent_id'), 'members', ['agent_id'], unique=False)
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=False)
    op.create_table('report_funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_parent_format', sa.String(length=100), nullable=True),
    sa.Column('deposit_count', sa.String(length=50), nullable=True),
    sa.Column('deposit_amount', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_count', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_amount', sa.String(length=50), nullable=True),
    sa.Column('charge_fee', sa.String(length=50), nullable=True),
    sa.Column('agent_commission', sa.String(length=50), nullable=True),
    sa.Column('promotion', sa.String(length=50), nullable=True),
    sa.Column('third_rebate', sa.String(length=50), nullable=True),
    sa.Column('third_activity_amount', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_funds_agent_id'), 'report_funds', ['agent_id'], unique=False)
    op.create_index(op.f('ix_report_funds_date'), 'report_funds', ['date'], unique=False)
    op.create_index(op.f('ix_report_funds_username'), 'report_funds', ['username'], unique=False)
    op.create_table('report_lottery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_parent_format', sa.String(length=100), nullable=True),
    sa.Column('bet_count', sa.String(length=50), nullable=True),
    sa.Column('bet_amount', sa.String(length=50), nullable=True),
    sa.Column('valid_amount', sa.String(length=50), nullable=True),
    sa.Column('rebate_amount', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('win_lose', sa.String(length=50), nullable=True),
    sa.Column('prize', sa.String(length=50), nullable=True),
    sa.Column('lottery_name', sa.String(length=200), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_lottery_agent_id'), 'report_lottery', ['agent_id'], unique=False)
    op.create_index(op.f('ix_report_lottery_username'), 'report_lottery', ['username'], unique=False)
    op.create_table('report_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('platform_id_name', sa.String(length=200), nullable=True),
    sa.Column('t_bet_times', sa.String(length=50), nullable=True),
    sa.Column('t_bet_amount', sa.String(length=50), nullable=True),
    sa.Column('t_turnover', sa.String(length=50), nullable=True),
    sa.Column('t_prize', sa.String(length=50), nullable=True),
    sa.Column('t_win_lose', sa.String(length=50), nullable=True),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_provider_agent_id'), 'report_provider', ['agent_id'], unique=False)
    op.create_index(op.f('ix_report_provider_report_date'), 'report_provider', ['report_date'], unique=False)
    op.create_index(op.f('ix_report_provider_username'), 'report_provider', ['username'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_key', sa.String(length=50), nullable=False),
    sa.Column('sync_date', sa.String(length=10), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'endpoint_key', 'sync_date', name='uq_sync_log')
    )
    op.create_index(op.f('ix_sync_log_agent_id'), 'sync_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sync_log_endpoint_key'), 'sync_log', ['endpoint_key'], unique=False)
    op.create_index(op.f('ix_sync_log_sync_date'), 'sync_log', ['sync_date'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_parent_format', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('user_fee', sa.String(length=50), nullable=True),
    sa.Column('true_amount', sa.String(length=50), nullable=True),
    sa.Column('status_format', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_agent_id'), 'withdrawals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_withdrawals_serial_no'), 'withdrawals', ['serial_no'], unique=False)
    op.create_index(op.f('ix_withdrawals_username'), 'withdrawals', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_username'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_serial_no'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_agent_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_sync_log_sync_date'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_endpoint_key'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_agent_id'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_report_provider_username'), table_name='report_provider')
    op.drop_index(op.f('ix_report_provider_report_date'), table_name='report_provider')
    op.drop_index(op.f('ix_report_provider_agent_id'), table_name='report_provider')
    op.drop_table('report_provider')
    op.drop_index(op.f('ix_report_lottery_username'), table_name='report_lottery')
    op.drop_index(op.f('ix_report_lottery_agent_id'), table_name='report_lottery')
    op.drop_table('report_lottery')
    op.drop_index(op.f('ix_report_funds_username'), table_name='report_funds')
    op.drop_index(op.f('ix_report_funds_date'), table_name='report_funds')
    op.drop_index(op.f('ix_report_funds_agent_id'), table_name='report_funds')
    op.drop_table('report_funds')
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.drop_index(op.f('ix_members_agent_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_invites_invite_code'), table_name='invites')
    op.drop_index(op.f('ix_invites_agent_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_deposits_username'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_agent_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_bets_username'), table_name='bets')
    op.drop_index(op.f('ix_bets_serial_no'), table_name='bets')
    op.drop_index(op.f('ix_bets_agent_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_bet_third_party_serial_no'), table_name='bet_third_party')
    op.drop_index(op.f('ix_bet_third_party_agent_id'), table_name='bet_third_party')
    op.drop_table('bet_third_party')
    # ### end Alembic commands ###
