"""widen_sync_date_to_varchar21

Revision ID: 9e8b8ddfc48e
Revises: 6f27ca2e7a16
Create Date: 2026-02-27 09:10:01.456575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8b8ddfc48e'
down_revision: Union[str, None] = '6f27ca2e7a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_log', 'sync_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=21),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_log', 'sync_date',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
