"""add_sync_date_lock_table

Revision ID: ac7458d95f37
Revises: 9e8b8ddfc48e
Create Date: 2026-02-27 10:25:22.055995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7458d95f37'
down_revision: Union[str, None] = '9e8b8ddfc48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_date_lock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_key', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_method', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'endpoint_key', 'date', name='uq_sync_date_lock')
    )
    op.create_index(op.f('ix_sync_date_lock_agent_id'), 'sync_date_lock', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sync_date_lock_date'), 'sync_date_lock', ['date'], unique=False)
    op.create_index(op.f('ix_sync_date_lock_endpoint_key'), 'sync_date_lock', ['endpoint_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_date_lock_endpoint_key'), table_name='sync_date_lock')
    op.drop_index(op.f('ix_sync_date_lock_date'), table_name='sync_date_lock')
    op.drop_index(op.f('ix_sync_date_lock_agent_id'), table_name='sync_date_lock')
    op.drop_table('sync_date_lock')
    # ### end Alembic commands ###
