"""add_source_id_and_unique_constraints

Revision ID: c27af6254163
Revises: 7d03c8a93299
Create Date: 2026-02-27 06:54:19.301491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27af6254163'
down_revision: Union[str, None] = '7d03c8a93299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bet_third_serial', 'bet_third_party', ['agent_id', 'serial_no'])
    op.create_unique_constraint('uq_bets_serial', 'bets', ['agent_id', 'serial_no'])
    op.add_column('invites', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invites_source_id'), 'invites', ['source_id'], unique=False)
    op.create_unique_constraint('uq_invites_source', 'invites', ['agent_id', 'source_id'])
    op.add_column('members', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_members_source_id'), 'members', ['source_id'], unique=False)
    op.create_unique_constraint('uq_members_source', 'members', ['agent_id', 'source_id'])
    op.create_unique_constraint('uq_withdrawals_serial', 'withdrawals', ['agent_id', 'serial_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_withdrawals_serial', 'withdrawals', type_='unique')
    op.drop_constraint('uq_members_source', 'members', type_='unique')
    op.drop_index(op.f('ix_members_source_id'), table_name='members')
    op.drop_column('members', 'source_id')
    op.drop_constraint('uq_invites_source', 'invites', type_='unique')
    op.drop_index(op.f('ix_invites_source_id'), table_name='invites')
    op.drop_column('invites', 'source_id')
    op.drop_constraint('uq_bets_serial', 'bets', type_='unique')
    op.drop_constraint('uq_bet_third_serial', 'bet_third_party', type_='unique')
    # ### end Alembic commands ###
